services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-app
    ports:
      - "80:80"    
    networks:
      - treesense-backend_app-network
    restart: unless-stopped


networks:
  treesense-backend_app-network:
    external: true